### PR TITLE
Add a link to The Lounge

### PR DESCRIPTION
**Pull request by xPaw**
Hi @erming! Hopefully you can accept this PR so users that stumble upon Shout are directed towards The Lounge.

We've been preparing v3.0 release, which is our biggest release so far, and we've been actively working on making documentation much better: https://next.thelounge.chat/docs/

Please come by our IRC channel so we can chat 😊

### CODE REVIEW

**Comment by erming** [comment]
Sure thing! Accepting the pull request.

The new website looks great! And I took the application for a spin; it both looks and works great. Lots of nice things. The new autocompletion is awesome, among lots of other things.

Send the team my regards — good job!

(Noticed that you mentioned me in the docs too. Thanks!)

**Comment by xPaw** [comment]
Very glad to hear that 💖

**Comment by astorije** [comment]
@erming! Glad to see you around! If you're interested...

➡️➡️[Fill this form](https://docs.google.com/forms/d/e/1FAIpQLSfv2K0o59Z5y09-ejZlVO8nPerylA8BXZ2tfpV6OJi8wCg2Vw/viewform) 😬 ⬅️⬅️

**Comment by richrd** [comment]
Seeing this I just wanted to say:
Even though this is a very small PR, it warms my heart because of this thread. This is a great example of the awesomeness of open source and people coming together. @erming you started all this and it's great to see how the seed you planted has grown and evolved. Thanks to everyone involved in both projects/forks! :gem: :heart:

**Pull request merged**
